version: '3'

# Services
services:
  # Apache + PHP
  php_recuperacion:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: 'php-recuperacion-server'
    volumes:
      - ./.docker/apache/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/apache/httpd.conf:/etc/apache2/conf-available/httpd.conf
      - ./.docker/apache/sites-available:/etc/apache2/sites-available
      - ./src/:/var/www/html
    expose:
      - 80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - db
    networks:
      - default
    ports:
      - '8098:80'
  db:
    image: mysql:8.0
    ports:
      - "3337:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: videoclub
      MYSQL_USER: usuario
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - persistent:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8037:80
    environment:
      MYSQL_USER: usuario
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
volumes:
  persistent:

    null
    # Lanzar con
    # docker-compose up -d --build

    # Ver los logs con
    # docker-compose logs -f

    # Bash: docker-compose exec apache_php_composer bash

    # https://www.bornfight.com/blog/blog-lamp-docker-setup-with-php-8-and-mariadb-for-symfony-projects/

    # https://www.cloudsavvyit.com/10528/how-to-use-docker-to-containerise-php-and-apache/

    # el host de la base de datos es el nombre de la imagen que aparece entre paréntesis
  # de la imagen 'mysql:8.0' ... por ejemplo (f95de814f6b4)